### ISSUE TITLE
Trying to exchange fo-dicom.Drawing with fo-dicom.DrawingHP

### ISSUE THREAD

**Issue by PalminX** [Efferent-Health/fo-dicom#3]
Hello,

in order to get JPEG Lossless support into a .NET Core project, I wanted to switch from using fo-dicom.Drawing to fo-dicom.DrawingHP.

I included the 4.0.20-efferent packages as described in https://github.com/Efferent-Health/fo-dicom/blob/development/NetCoreHP.md, but get the following compile errors under Windows:

```
1>Controllers\InstanceMetadataController.cs(40,37,40,69): error CS0012: The type 'DicomDataset' is defined in an assembly that is not referenced. You must add a reference to assembly 'Dicom.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.
1>Controllers\InstanceMetadataController.cs(42,17,42,65): error CS0012: The type 'DicomDataset' is defined in an assembly that is not referenced. You must add a reference to assembly 'Dicom.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.
1>Controllers\RenderedImageController.cs(38,35,38,65): error CS0012: The type 'DicomImage' is defined in an assembly that is not referenced. You must add a reference to assembly 'Dicom.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.
1>Controllers\RenderedImageController.cs(39,37,39,69): error CS0012: The type 'DicomDataset' is defined in an assembly that is not referenced. You must add a reference to assembly 'Dicom.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.
1>Controllers\RenderedImageController.cs(41,35,41,51): error CS0012: The type 'DicomImage' is defined in an assembly that is not referenced. You must add a reference to assembly 'Dicom.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.
1>Startup.cs(71,65,71,73): error CS0012: The type 'ImageManager' is defined in an assembly that is not referenced. You must add a reference to assembly 'Dicom.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.
```

Do you have an idea what I am doing wrong here?

**Comment by jaime-olivares** [comment]
You can safely dismiss that document. It is for building the Nuget package.

Include the following packages in your csproj file and you should be all set:
````
    <PackageReference Include="fo-dicom.NetCoreHP" Version="4.0.20-efferent"/>
    <PackageReference Include="fo-dicom.DrawingHP" Version="4.0.20-efferent"/>
````

**Comment by PalminX** [comment]
I did that, this is the part of the NetCoreHP.md I used... 
The packages are also shown in Visual Studio as Dependencies, but compilation fails.

**Comment by jaime-olivares** [comment]
NetCoreHP.md has no relationship with the usage of the library. Please don't follow it.

Did you use NetCoreHP as well, besides DrawingHP? Can you post your csproj?

**Comment by PalminX** [comment]
This is part of my csproj:

```
  <ItemGroup>
    <PackageReference Include="fo-dicom.NetCoreHP" Version="4.0.20-efferent"/>
    <PackageReference Include="fo-dicom.DrawingHP" Version="4.0.20-efferent"/>
    <PackageReference Include="System.ComponentModel.Composition" Version="4.5.0"/>
    <PackageReference Include="fo-dicom.Json" Version="4.0.1">
      <NoWarn>NU1701</NoWarn>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Cors" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.1" />
  </ItemGroup>
```

**Comment by jaime-olivares** [comment]
I think your problem is generated by fo-dicom.Json, it is requiring the original fo-dicom library.
I have never used that package in my projects, but I guess it will require a treatment exactly as DrawingHP, this is: to create a fo-dicom.JsonHP package, so all modules will be using the same fo-dicom variant.

**Comment by jaime-olivares** [comment]
Please wait for news at the end of the day. I am trying with a totally different approach for this library.

**Comment by PalminX** [comment]
Thanks!

**Comment by jaime-olivares** [comment]
Please have a look at this new project:
https://github.com/Efferent-Health/Dicom-native

We are incorporating the last tests and then will release a Nuget package today.
That project will replace this one, and is more isolated from fo-dicom.

**Comment by jaime-olivares** [comment]
The new project is completed and fully tested on windows and ubuntu
